### ISSUE TITLE
illegal base64 data when decoding keys

### ISSUE THREAD

**Issue by jonmclachlanatpurestorage** [coreos/go-oidc#193] opened 2019-03-12 00:29 UTC
Using version `v2` latest and `v2.0.0`, I noticed that when a well configured internal IdP provides the response,
```
{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "alg": "RS256",
      "kid": "Ow9jxPbGhteqL/y8shzj5I1tJMUe",
      "n": "ANTpYd-HJzCRa6jkyQaqGn9clDVdB4WdsqkDt0_I9TTfmbTq5UXmhYEvNsjYo00UAt1Mni3vuhpZzHzZ-V4qkfL5mAsrNZWQ-fmsnWGt9lXn_S2chdxqkdq8DLszGJvCDHih-TK_KVNQDJ5IKA5kNDYAiSetKYrx2KFUmGGjG9agd2v7mFW0vlvB7sYZAOlzATNMrp73NJdaRK-4zpk_kxjdRAqeuUcNCq3XgYmhwovTaBd7VIXz4VCoGqKWOTJeeHgY8Upwk1GPzOhD_TsEWhS1Ab1vmqUndRU1DthNlzLgJQ288ZQpxg8l6POA6FIFKTBYEN6Gx5cdgTTpQRpd5U8=",
      "e": "AQAB"
    }
  ]
}
```

During key discovery, that attempts to verify the tokens results in the error message,

```
failed to verify signature: fetching keys oidc: failed to decode keys: got Content-Type = application/json, but could not unmarshal as JSON: illegal base64 data at input byte 343 {"keys":[{"kty":"RSA","use":"sig","alg":"RS256","kid":"Ow9jxPbGhteqL/y8shzj5I1tJMUe","n":"ANTpYd-HJzCRa6jkyQaqGn9clDVdB4WdsqkDt0_I9TTfmbTq5UXmhYEvNsjYo00UAt1Mni3vuhpZzHzZ-V4qkfL5mAsrNZWQ-fmsnWGt9lXn_S2chdxqkdq8DLszGJvCDHih-TK_KVNQDJ5IKA5kNDYAiSetKYrx2KFUmGGjG9agd2v7mFW0vlvB7sYZAOlzATNMrp73NJdaRK-4zpk_kxjdRAqeuUcNCq3XgYmhwovTaBd7VIXz4VCoGqKWOTJeeHgY8Upwk1GPzOhD_TsEWhS1Ab1vmqUndRU1DthNlzLgJQ288ZQpxg8l6POA6FIFKTBYEN6Gx5cdgTTpQRpd5U8=","e":"AQAB"}]}
```

I can repro the issue with this small program,
```
package main

import (
	"gopkg.in/square/go-jose.v2"
	"encoding/json"
	"log"
)

func main() {
	x := "{\"keys\":[{\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"kid\":\"Ow9jxPbGhteqL/y8shzj5I1tJMUe\",\"n\":\"ANTpYd-HJzCRa6jkyQaqGn9clDVdB4WdsqkDt0_I9TTfmbTq5UXmhYEvNsjYo00UAt1Mni3vuhpZzHzZ-V4qkfL5mAsrNZWQ-fmsnWGt9lXn_S2chdxqkdq8DLszGJvCDHih-TK_KVNQDJ5IKA5kNDYAiSetKYrx2KFUmGGjG9agd2v7mFW0vlvB7sYZAOlzATNMrp73NJdaRK-4zpk_kxjdRAqeuUcNCq3XgYmhwovTaBd7VIXz4VCoGqKWOTJeeHgY8Upwk1GPzOhD_TsEWhS1Ab1vmqUndRU1DthNlzLgJQ288ZQpxg8l6POA6FIFKTBYEN6Gx5cdgTTpQRpd5U8=\",\"e\":\"AQAB\"}]}"
	var into jose.JSONWebKeySet
	err := json.Unmarshal([]byte(x), &into)
	if err != nil {
		log.Println("Failed due to error, ", err)
	}
}
```

The issue seems to be that the parameters for `n` is being decoded as a url string, and not as base64url.

Decoded as URL (matches error):
![Screen Shot 2019-03-11 at 5 26 11 PM](https://user-images.githubusercontent.com/48459999/54166556-04685000-4423-11e9-99a4-2bcec77a4089.png)

Decoded as base64Url (should have been):
![Screen Shot 2019-03-11 at 5 27 02 PM](https://user-images.githubusercontent.com/48459999/54166579-1b0ea700-4423-11e9-96b2-0cfe6417fe40.png)

I guess there's something about this particular `n` that results in an invalid char at offset 343 that has just gone unnoticed until now.

**Comment by ericchiang** [comment] 2019-03-12 00:35
Thanks for the standalone reproducer!

It looks like N has padding, even though the jose specs use unpadded base64 https://tools.ietf.org/html/rfc7515#appendix-C

We're probably not going to address this since it's go-jose that's rejecting the key though. You'll likely need to fix your internal IdP

**Comment by jonmclachlanatpurestorage** [comment] 2019-03-12 00:39
Thx for quick reply, and thx to the reference to the spec. Let me double check if our IdP is diverging from the spec, of course that's where the fix should go. :)

**Comment by ericchiang** [comment] 2019-03-12 02:14
Good to hear! I'm going to close this issue for now since I think we've identified the root issue. Please comment if you think you've found a bug in go-oidc

**Closed as completed by ericchiang** 2019-03-12 02:14 UTC
