### ISSUE TITLE
Azure's OpenID Connect metadata document has a dynamic issuer

### ISSUE THREAD

**Issue by autom8ter** [coreos/go-oidc#245] opened 2020-04-28 22:45 UTC
We only allow organizations to authenticate via Azure Open ID Connect, but the library does not support this and prints: 
oidc: issuer did not match the issuer returned by provider, expected \"https://login.microsoftonline.com/organizations/v2.0\" got \"https://login.microsoftonline.com/{tenantid}/v2.0\

Reference: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

**Comment by ericchiang** [comment] 2020-04-28 22:57
Duplicate of https://github.com/coreos/go-oidc/issues/212

**Closed as completed by ericchiang** 2020-04-28 22:57 UTC
